// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: pjylbisbkucwqfmxlhwk

class SupabaseConfig {
  static const String supabaseUrl = 'https://pjylbisbkucwqfmxlhwk.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqeWxiaXNia3Vjd3FmbXhsaHdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU5NTM5MzIsImV4cCI6MjA4MTUyOTkzMn0.nXHktmvRTGb3S1JbtrmC_uLXxU_Se0KTc6lykMggeaY';
}
